import { artifactEnvelope } from './contracts.js';
import { TRUTH_VERSION } from './support-guard.js';

const DRAFT_SCHEMA={type:'object',additionalProperties:false,required:['sentences'],properties:{sentences:{type:'array',minItems:1,maxItems:24,items:{type:'object',additionalProperties:false,required:['text','evidenceIds'],properties:{text:{type:'string',minLength:1,maxLength:900},evidenceIds:{type:'array',maxItems:6,items:{type:'string'}},claimIds:{type:'array',maxItems:6,items:{type:'string'}},kind:{enum:['factual','qualification','transition']}}}}}};
function parse(text){try{return JSON.parse(String(text||'').trim());}catch{return null;}}
function packetEvidenceIds(contextPacket){const explicit=contextPacket?.payload?.includedEvidenceIds;if(Array.isArray(explicit))return explicit;return [...new Set((contextPacket?.payload?.claimCoverage||[]).flatMap(c=>c.includedEvidenceIds||[]))];}
function fallbackSentences(claims,evidence,allowed,omittedClaimIds=new Set()){
const out=[];for(const claim of claims){if(omittedClaimIds.has(claim.id)){out.push({text:`I could not include enough verified evidence for ${claim.text.replace(/[?.!]+$/u,'')} within the selected model context.`,evidenceIds:[],claimIds:[claim.id],kind:'qualification'});continue;}const rows=evidence.filter(a=>a.payload?.accepted&&allowed.has(a.artifactId)&&a.payload.claimId===claim.id);if(claim.status==='disputed'){out.push({text:`The available sources disagree on ${claim.text.replace(/[?.!]+$/u,'')}.`,evidenceIds:rows.map(a=>a.artifactId).slice(0,4),claimIds:[claim.id],kind:'qualification'});continue;}for(const row of rows.slice(0,2))out.push({text:row.payload.statement,evidenceIds:[row.artifactId],claimIds:[claim.id],kind:'factual'});if(!rows.length&&['unresolved','unresearched','weak'].includes(claim.status))out.push({text:`I could not verify ${claim.text.replace(/[?.!]+$/u,'')} reliably from the available evidence.`,evidenceIds:[],claimIds:[claim.id],kind:'qualification'});}return out;}
export async function draftResearchAnswer({runId,question,claims,contextPacket,evidenceArtifacts,targetExecutor,targetId=null,signal=null,nodeId='research-answer',allowFallback=true}={}){
  const packetIds=new Set(packetEvidenceIds(contextPacket));const acceptedRecords=evidenceArtifacts.filter(a=>a.payload?.accepted&&packetIds.has(a.artifactId));const accepted=new Set(acceptedRecords.map(a=>a.artifactId));const allStructuredExact=acceptedRecords.length>0&&acceptedRecords.every(a=>a.payload?.provenance?.structuredEvidence?.kind==='wikidata-current-office');let sentences=null;let telemetry=null;let method='deterministic-evidence';
  if(targetExecutor&&!allStructuredExact){const system='Write a concise, direct answer to the QUESTION from the supplied ACCEPTED_EVIDENCE_PACKET only. Return JSON. State what the subject is or what happened; never write vague filler such as “is explained by the evidence”. Every factual sentence must list the exact evidence IDs that support it. Never use knowledge outside the packet. If evidence is disputed or weak, say so. Do not cite an ID you were not given. Transition sentences may have no evidence IDs but may not add facts.';const user=JSON.stringify({QUESTION:question,CLAIMS:claims.map(c=>({id:c.id,text:c.text,evidenceQuery:c.evidenceQuery||c.text,status:c.status})),ACCEPTED_EVIDENCE_PACKET:contextPacket.payload.packetText,ALLOWED_EVIDENCE_IDS:[...accepted]});try{const result=await targetExecutor.complete({system,user,schema:DRAFT_SCHEMA,signal,maxTokens:1200,stageId:'research-answer',runId,targetId,allowFallback});telemetry=result;const value=parse(result.text);if(value&&Array.isArray(value.sentences)){const valid=value.sentences.filter(s=>s&&typeof s.text==='string'&&Array.isArray(s.evidenceIds)&&s.evidenceIds.every(id=>accepted.has(id))).map(s=>({text:String(s.text).trim(),evidenceIds:[...new Set(s.evidenceIds)],claimIds:Array.isArray(s.claimIds)?s.claimIds.filter(id=>claims.some(c=>c.id===id)):[],kind:s.kind||'factual'})).filter(s=>s.text&&!/\b(?:is|are|was|were)\s+(?:explained|described|covered|shown)\s+(?:through|by|in)\s+(?:the\s+)?(?:available\s+)?evidence\b/iu.test(s.text));if(valid.length){sentences=valid;method='structured-grounded-draft';}}}catch{}}
  if(!sentences)sentences=fallbackSentences(claims,evidenceArtifacts,accepted,new Set(contextPacket?.payload?.omittedCriticalScope||[]));return{artifact:artifactEnvelope({type:'AnswerDraft',runId,nodeId,payload:{truthVersion:TRUTH_VERSION,question,sentences,method,tokenStats:telemetry?{input:telemetry.inputTokens,inputEstimated:telemetry.inputEstimated,output:telemetry.outputTokens,outputEstimated:telemetry.outputEstimated}:null},inputRefs:[contextPacket.artifactId,...sentences.flatMap(s=>s.evidenceIds)],retentionClass:'interrupted-run'}),telemetry};
}
