import { artifactEnvelope } from './contracts.js';
import { supportGuard, canonicalAtomicValue, compareAtomicValues, TRUTH_VERSION } from './support-guard.js';

function sensitiveTask(task){return['medicine','law','finance-business','government-public-office','current-news','science'].includes(task);}
function acceptableSource(profile,task){if(profile?.userOverride==='never')return false;const tier=Number(profile?.taskTier??3);if(sensitiveTask(task))return tier<=3&&!profile?.classIds?.includes('aggregator');return tier<=4;}
function independence(page){return page.lineageId||page.domain||page.url;}
function primaryRole(profile,pageRole){return /primary|official|regulator|standard/u.test(String(profile?.evidenceRole||''))||['primary-document','official-overview'].includes(pageRole?.kind);}
function supportStrength(fact,_profile,{pageRole=null,structuredEvidence=null}={}){if(!['supports','contradicts'].includes(fact.stance))return'weak';let directness=2;if(pageRole?.kind==='primary-document'||structuredEvidence?.kind==='wikidata-current-office')directness+=1;if(['identity','date','number','status'].includes(fact.factKind)&&fact.atomicValue)directness+=1;return directness>=4?'strong':'moderate';}

function claimRelevance(claimText,statement){const stop=new Set(['what','when','where','which','with','from','that','this','current','latest','official','the','and','for','are','was','were','who','why','how']);const terms=v=>(String(v||'').toLocaleLowerCase().match(/[\p{L}\p{N}]{3,}/gu)||[]).filter(x=>!stop.has(x));const a=[...new Set(terms(claimText))],b=new Set(terms(statement));if(!a.length)return 0;return Number((a.filter(x=>b.has(x)).length/a.length).toFixed(3));}
function credibleContradiction(record){return ['moderate','strong'].includes(record?.payload?.strength)&&Number(record?.payload?.sourceQuality?.taskTier??5)<=3;}
function parseTimestamp(value){const ms=Date.parse(String(value||''));return Number.isFinite(ms)?ms:null;}
const HOUR=60*60*1000, DAY=24*HOUR;
function freshnessHorizon(claim,task){if(claim?.freshness!=='high')return{kind:'stable-or-medium',ms:null};const q=String(claim?.text||'').toLocaleLowerCase();if(/\b(?:price|weather|temperature|exchange rate|fx|score|outage|down|availability|trading at|worth now|live)\b/u.test(q))return{kind:'live',ms:2*DAY};if(task==='current-news')return{kind:'news',ms:30*DAY};if(task==='finance-business')return{kind:'market-current',ms:14*DAY};if(task==='government-public-office')return{kind:'current-office',ms:180*DAY};if(task==='law')return{kind:'law-current',ms:365*DAY};if(task==='software')return{kind:'software-current',ms:730*DAY};if(task==='medicine'||task==='science')return{kind:'research-current',ms:5*365*DAY};return{kind:'current-general',ms:180*DAY};}
function undatedAuthoritativeEligible(claim,task,profile,pageRole,url=''){if(!primaryRole(profile,pageRole))return false;let path='';try{path=new URL(url||'https://invalid.local/').pathname.toLocaleLowerCase();}catch{}const q=String(claim?.text||'').toLocaleLowerCase();if(task==='government-public-office')return /\/(?:leadership|leaders?|officials?|president|minister|cabinet|administration|team|office|about)(?:\/|$)/u.test(path)||/\b(?:leadership|officials?|president|prime minister|cabinet)\b/u.test(q)&&path==='/' ;if(task==='software')return /\/(?:docs?|reference|releases?|changelog|current|status)(?:\/|$)/u.test(path);if(/\b(?:status|outage|availability)\b/u.test(q))return /\/(?:status|health)(?:\/|$)/u.test(path);return false;}
function freshnessAssessment(claim,timestampHint,task,profile,pageRole,url='',now=Date.now()){
  const horizon=freshnessHorizon(claim,task);if(horizon.ms===null)return{satisfied:true,horizonKind:horizon.kind,horizonMs:null,timestampBasis:'not-required',ageMs:null,reason:'FRESHNESS_NOT_REQUIRED'};
  const stamp=parseTimestamp(timestampHint);if(stamp!==null){const futureMs=stamp-now;if(futureMs>DAY)return{satisfied:false,horizonKind:horizon.kind,horizonMs:horizon.ms,timestampBasis:'parsed-timestamp',ageMs:null,reason:'FUTURE_TIMESTAMP'};const age=Math.max(0,now-stamp);return{satisfied:age<=horizon.ms,horizonKind:horizon.kind,horizonMs:horizon.ms,timestampBasis:'parsed-timestamp',ageMs:age,reason:age<=horizon.ms?'WITHIN_HORIZON':'STALE_EVIDENCE'};}
  // Current official/primary rosters and live project/status pages are often undated.
  // They may satisfy freshness only when their structural source role is authoritative;
  // absence of a timestamp alone never upgrades a contextual page.
  if(undatedAuthoritativeEligible(claim,task,profile,pageRole,url))return{satisfied:true,horizonKind:horizon.kind,horizonMs:horizon.ms,timestampBasis:'undated-authoritative-live-page',ageMs:null,reason:'CURRENT_ROLE_WITHOUT_DATE'};
  return{satisfied:false,horizonKind:horizon.kind,horizonMs:horizon.ms,timestampBasis:'missing',ageMs:null,reason:'FRESHNESS_UNESTABLISHED'};
}
function groundedFact(fact,refs){const sources=refs.map(a=>a?.payload?.text||'').filter(Boolean);if(!sources.length)return{ok:false,statement:{supported:false,status:'unsupported',reason:'NO_SOURCE'},atomic:null};const statement=supportGuard(fact.statement,sources,'paraphrase');if(!statement.supported)return{ok:false,statement,atomic:null};const atomic=fact.atomicValue?supportGuard(fact.atomicValue,sources,'paraphrase'):null;if(atomic&&!atomic.supported)return{ok:false,statement,atomic};return{ok:true,statement,atomic};}
function directlyAnswersClaim(claim,fact,refs=[]){const query=String(claim?.evidenceQuery||claim?.text||'');const statement=String(fact?.statement||'');const source=refs.map(item=>String(item?.payload?.text||'')).join(' ');if(/\blts\b/iu.test(query)&&(!/\blts\b/iu.test(statement)||!/\blts\b/iu.test(source)))return false;if(/\bwhen\b.{0,160}\b(?:built|constructed|completed|founded|established|opened|created)\b|\b(?:construction\s+)?completed\s+year\b/iu.test(query)){const direct=value=>/\b(?:1\d{3}|20\d{2})\b/u.test(value)&&/\b(?:built|construct(?:ed|ion)?|completed?|completion|founded|established|opened|created|began|started)\b/iu.test(value);return direct(statement)&&direct(source);}const definition=query.match(/^\s*(?:what\s+is|define)\s+(?:an?\s+|the\s+)?(.+?)[?.!]*\s*$/iu);if(definition){const subject=String(definition[1]||'').toLocaleLowerCase().replace(/[^\p{L}\p{N}\s-]+/gu,' ').replace(/\s+/gu,' ').trim();const text=statement.toLocaleLowerCase();const index=subject?text.indexOf(subject):-1;if(index<0||index>50)return false;const tail=text.slice(index+subject.length,index+subject.length+180);return /^(?:\s|[,—:-]|\[[^\]]{1,100}\])*(?:(?:is|are)\s+(?:an?\s+|the\s+)?(?:\w+\s+){0,3}(?:process|phenomenon|concept|method|system|type|form|conversion|mechanism)\b|means?\b|refers?\s+to\b)/u.test(tail);}return true;}
function openInformationRequest(claim){const text=String(claim?.text||'').trim();return /^(?:look\s*up|search(?:\s+for)?|find|tell\s+me|name|identify|who|what|when|where|which|how\s+(?:many|much|old|long))\b/iu.test(text);}
function calibratedStance(claim,fact,direct){if(fact?.stance==='contradicts'&&direct&&openInformationRequest(claim))return'supports';return fact?.stance;}
export function evidenceFromDossier(dossierArtifact,excerptArtifacts,{runId,claims=[],taskProfile='general-reference',nodeId='research-evidence'}={}){
  const d=dossierArtifact.payload;const excerpts=new Map(excerptArtifacts.map(a=>[a.artifactId,a]));const profile=d.sourceProfile||{};const artifacts=[];
  for(const fact of d.facts||[]){
    const claim=claims.find(c=>c.id===fact.claimId);if(!claim)continue;
    const refs=(fact.excerptIds||[]).map(id=>excerpts.get(id)).filter(Boolean);
    const sourceOk=acceptableSource(profile,taskProfile);const support=refs.length?groundedFact(fact,refs):{ok:false,statement:{supported:false,status:'unsupported',reason:'MISSING_PROVENANCE'},atomic:null};
    const freshness=freshnessAssessment(claim,d.timestampHint,taskProfile,profile,d.pageRole||null,d.url||'');const direct=directlyAnswersClaim(claim,fact,refs);
    const stance=calibratedStance(claim,fact,direct);const accepted=refs.length>0&&sourceOk&&support.ok&&freshness.satisfied&&direct&&stance!=='related';
    let rejectionReason=null;if(!refs.length)rejectionReason='MISSING_PROVENANCE';else if(!freshness.satisfied)rejectionReason=['STALE_EVIDENCE','FUTURE_TIMESTAMP'].includes(freshness.reason)?freshness.reason:'FRESHNESS_UNESTABLISHED';else if(!support.ok)rejectionReason='BAD_EXCERPT_SUPPORT';else if(!direct)rejectionReason='QUESTION_NOT_ANSWERED';else if(!sourceOk||stance==='related')rejectionReason='INSUFFICIENT_CLAIM_SUPPORT';
    const canonicalAtomic=fact.atomicValue?canonicalAtomicValue(fact.factKind||'other',fact.atomicValue):null;
    const strength=supportStrength({...fact,stance},profile,{pageRole:d.pageRole||null,structuredEvidence:d.structuredEvidence||null});const payload={truthVersion:TRUTH_VERSION,claimId:claim.id,sourceId:dossierArtifact.artifactId,excerptIds:refs.map(a=>a.artifactId),stance,strength,independenceGroup:independence(d),accepted,rejectionReason,statement:fact.statement,factKind:fact.factKind||'other',atomicValue:fact.atomicValue||null,canonicalAtomicValue:canonicalAtomic,support:{status:support.statement?.status||'unsupported',reason:support.statement?.reason||null,atomicStatus:support.atomic?.status||null,atomicReason:support.atomic?.reason||null},freshness,sourceQuality:{taskTier:Number(profile.taskTier??3),classIds:[...(profile.classIds||[])],anchor:Boolean(profile.anchor),acceptable:sourceOk},evidenceDimensions:{claimRelevance:claimRelevance(claim.evidenceQuery||claim.text,fact.statement),pageRole:d.pageRole?.kind||'contextual',freshnessSatisfied:Boolean(freshness.satisfied),supportStatus:support.statement?.status||'unsupported',directness:strength,reportedStance:fact.stance},provenance:{url:d.url,domain:d.domain,dossierId:dossierArtifact.artifactId,timestampHint:d.timestampHint||null,evidenceRole:profile.evidenceRole||null,sourceClasses:[...(profile.classIds||[])],taskTier:Number(profile.taskTier??3),anchor:Boolean(profile.anchor),pageRole:d.pageRole||null,publisherGroup:d.publisherGroup||d.lineageId||null,contentLineageId:d.contentLineageId||null,structuredEvidence:d.structuredEvidence?{kind:d.structuredEvidence.kind,officeId:d.structuredEvidence.officeId,personId:d.structuredEvidence.personId,retrievedAt:d.structuredEvidence.retrievedAt}:null}};
    artifacts.push(artifactEnvelope({type:'EvidenceRecord',runId,nodeId,payload,inputRefs:[dossierArtifact.artifactId,...payload.excerptIds],provenanceRefs:[d.url,...payload.excerptIds],retentionClass:'interrupted-run'}));
  }
  return artifacts;
}
function typedAtomicConflicts(records){const rows=records.filter(a=>['identity','date','number','status'].includes(a.payload.factKind)&&a.payload.atomicValue).map(a=>({id:a.artifactId,raw:a.payload.atomicValue,kind:a.payload.factKind,group:a.payload.independenceGroup,canonical:a.payload.canonicalAtomicValue||canonicalAtomicValue(a.payload.factKind,a.payload.atomicValue)}));const conflicts=[];for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){if(rows[i].kind!==rows[j].kind)continue;const cmp=compareAtomicValues(rows[i].kind,rows[i].raw,rows[j].raw);if(cmp.relation==='conflict')conflicts.push({left:rows[i],right:rows[j],comparison:cmp});}return{rows,conflicts};}
export function reconcileClaims(claims,evidenceArtifacts,{runId,nodeId='research-evidence'}={}){
  const updated=[];const conflicts=[];
  for(const claim of claims){
    const records=evidenceArtifacts.filter(a=>a.payload.claimId===claim.id&&a.payload.accepted);
    const supporting=records.filter(a=>a.payload.stance==='supports');const contradicting=records.filter(a=>a.payload.stance==='contradicts');
    const groups=[...new Set(supporting.map(a=>a.payload.independenceGroup).filter(Boolean))];const req=claim.evidenceRequirement||{minAccepted:1,minIndependent:1};const credibleOpposition=contradicting.filter(credibleContradiction);const weakOpposition=contradicting.filter(a=>!credibleContradiction(a));let status='weak';
    if(!records.length)status='unresearched';else if(credibleOpposition.length)status='disputed';else if(weakOpposition.length)status='weak';else if(supporting.length>=req.minAccepted&&groups.length>=req.minIndependent){if(supporting.some(a=>a.payload.strength==='strong'))status='strong';else if(supporting.some(a=>a.payload.strength==='moderate'))status='supported';else status='weak';}
    const atomic=typedAtomicConflicts(supporting);if(atomic.conflicts.length){status='disputed';const conflict=artifactEnvelope({type:'Conflict',runId,nodeId,payload:{truthVersion:TRUTH_VERSION,claimId:claim.id,reason:'ATOMIC_VALUE_DISAGREEMENT',values:atomic.rows,comparisons:atomic.conflicts},inputRefs:[...new Set(atomic.conflicts.flatMap(x=>[x.left.id,x.right.id]))],retentionClass:'interrupted-run'});conflicts.push(conflict);}
    else if(credibleOpposition.length){const conflict=artifactEnvelope({type:'Conflict',runId,nodeId,payload:{truthVersion:TRUTH_VERSION,claimId:claim.id,reason:'CONTRADICTING_EVIDENCE',supportingEvidenceIds:supporting.map(a=>a.artifactId),contradictingEvidenceIds:credibleOpposition.map(a=>a.artifactId),weakContradictingEvidenceIds:weakOpposition.map(a=>a.artifactId)},inputRefs:[...supporting,...credibleOpposition].map(a=>a.artifactId),retentionClass:'interrupted-run'});conflicts.push(conflict);}
    updated.push({...claim,status,supportingEvidenceIds:supporting.map(a=>a.artifactId),contradictingEvidenceIds:contradicting.map(a=>a.artifactId),independenceGroups:groups,weakContradictingEvidenceIds:weakOpposition.map(a=>a.artifactId),contradictionStrength:credibleOpposition.length?'credible':weakOpposition.length?'weak':null,resolution:status==='disputed'?'requires-targeted-resolution':weakOpposition.length?'contradiction-needs-corroboration':status==='unresearched'?null:'evidence-evaluated'});
  }
  return{claims:updated,conflicts};
}
