import crypto from 'node:crypto';
import { classifyWebFailure } from '../web/failure.js';
import { createSourceOperations } from './source-ledger.js';

const MIN_DIRECT_TEXT=500;const MAX_EXCERPTS=4;const MAX_EXCERPT_CHARS=1800;

const HOSTILE_INSTRUCTION = /(?:ignore|disregard|override|forget)\s+(?:all\s+|any\s+|the\s+)?(?:previous|prior|system|developer|assistant)?\s*instructions?|(?:system|developer|assistant)\s+prompt|(?:call|invoke|use)\s+(?:a\s+|the\s+)?tools?|(?:save|write|add|store)\s+(?:this\s+|the\s+)?memory|reveal\s+(?:the\s+)?(?:system\s+)?prompt|follow\s+these\s+instructions|do\s+not\s+(?:follow|obey)\s+(?:the\s+)?(?:previous|system|developer)/iu;
const INJECTION_RESEARCH = /prompt\s+injection|jailbreak|system\s+prompt|ignore\s+(?:all\s+)?previous\s+instructions?/iu;
export function sanitizeExternalExcerpt(text,{queryText=''}={}){const value=clean(text);if(!value||INJECTION_RESEARCH.test(String(queryText||'')))return{safeText:value,hostileInstructionDetected:false};let hostile=false;const units=value.split(/(?<=[.!?])\s+|\n+/u).map(x=>x.trim()).filter(Boolean);const safe=units.filter(unit=>{if(HOSTILE_INSTRUCTION.test(unit)){hostile=true;return false;}return true;});return{safeText:clean(safe.join(' ')),hostileInstructionDetected:hostile};}
function clean(v){return String(v??'').normalize('NFC').replace(/\r/gu,'').replace(/[\t ]+/gu,' ').replace(/ *\n */gu,'\n').replace(/\n{3,}/gu,'\n\n').trim();}
function host(url=''){try{return new URL(url).hostname.toLowerCase().replace(/^www\./u,'');}catch{return'';}}
function hash(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
function terms(values=[]){const out=new Set(values.flatMap(v=>clean(v).toLocaleLowerCase().match(/[\p{L}\p{N}]{3,}/gu)||[]).filter(x=>!['the','and','between','difference','different','explain','compare','versus','what','when','where','which','with','from','that','this','have','does','about','current','latest','official','independent','report','source'].includes(x)));if(out.has('built'))for(const synonym of ['construct','constructed','construction','completed','completion','began','started'])out.add(synonym);return out;}
function scoreParagraph(p,wanted,{temporal=false,definitionSubject='',comparisonTerms=[]}={}){const low=p.toLocaleLowerCase();let score=0;for(const t of wanted)if(low.includes(t))score+=1;const years=(p.match(/\b(?:1\d{3}|20\d{2})\b/gu)||[]).length;score+=Math.min(2,years);if(temporal&&years&&/\b(?:built|construct(?:ed|ion)?|completed?|completion|founded|established|opened|created|began|started)\b/iu.test(p))score+=5;if(definitionSubject){const escaped=definitionSubject.replace(/[.*+?^${}()|[\]\\]/gu,'\\$&');if(new RegExp(`(?:^|[.!?]\\s+)(?:the\\s+)?${escaped}(?:\\s*\\[[^\\]]{1,100}\\])?\\s+(?:is|are|means?|refers?\\s+to)\\b`,'iu').test(p))score+=10;}if(comparisonTerms.length){const hits=comparisonTerms.filter(term=>low.includes(term)).length;if(hits&&/\b(?:is|are|means?|measures?|depends?|force|amount|unit|whereas|while|unlike|gravity|kilograms?|newtons?)\b/iu.test(p))score+=hits*6;if(hits===comparisonTerms.length)score+=4;}return score;}
function chunks(text){const paras=clean(text).split(/\n{2,}|(?<=[.!?])\s+(?=[A-Z\p{Lu}])/u).map(x=>x.trim()).filter(x=>x.length>=20);return paras;}
export function selectRelevantExcerpts(page,{question='',claims=[]}={}){const queryText=[question,...claims.map(c=>c.text||c)].join(' ');const wanted=terms([queryText]);const temporal=/\bwhen\b.{0,160}\b(?:built|constructed|completed|founded|established|opened|created)\b|\b(?:construction\s+)?completed\s+year\b/iu.test(queryText);const definitionMatch=clean(question).match(/^\s*(?:what\s+is|define)\s+(?:an?\s+|the\s+)?(.+?)[?.!]*\s*$/iu);const definitionSubject=clean(definitionMatch?.[1]||'').toLocaleLowerCase();const comparison=clean(question).match(/\b(?:difference\s+between|compare)\s+(.+?)\s+(?:and|with|versus|vs\.?)\s+(.+?)[?.!]*$/iu);const comparisonTerms=[...terms([comparison?.[1]||'',comparison?.[2]||''])];const scoring={temporal,definitionSubject,comparisonTerms};const titleScore=scoreParagraph(clean(page?.title||''),wanted,scoring);const ranked=chunks(page.text).map((text,index)=>{const sanitized=sanitizeExternalExcerpt(text,{queryText});return{text:sanitized.safeText,index,score:scoreParagraph(sanitized.safeText,wanted,scoring)+(index<2?titleScore:0),hostileInstructionDetected:sanitized.hostileInstructionDetected};}).filter(item=>item.text.length>=20&&(!wanted.size||item.score>0)).sort((a,b)=>b.score-a.score||a.index-b.index);const picked=[];for(const item of ranked){if(picked.length>=MAX_EXCERPTS)break;const text=item.text.slice(0,MAX_EXCERPT_CHARS);if(picked.some(x=>x.text===text))continue;picked.push({id:`x${picked.length+1}`,text,startOrdinal:item.index,score:item.score,exact:true,hostileInstructionDetected:item.hostileInstructionDetected});}return picked.sort((a,b)=>a.startOrdinal-b.startOrdinal);}
export function classifyPageContent(page){const body=clean(page.text||'');const text=clean(`${page.title||''}\n${body}`).slice(0,7000);const low=text.toLocaleLowerCase();const challenge=/\b(?:captcha|verify you are human|are you a robot|security check)\b/u.test(low);if(challenge&&(body.length<2500||/\b(?:captcha|verify you are human|are you a robot)\b/u.test(clean(page.title).toLocaleLowerCase())))return{usable:false,code:'WEB_CAPTCHA',reason:'challenge'};if((/\b(?:sign in|log in|login required|members only)\b/u.test(low)&&body.length<2500))return{usable:false,code:'WEB_LOGIN',reason:'login'};if((/\b(?:subscribe to continue|subscription required|this article is for subscribers|unlock this article|paywall)\b/u.test(low)&&body.length<5000))return{usable:false,code:'WEB_PAYWALL',reason:'paywall'};if(body.length<120)return{usable:false,code:'WEB_EXTRACT_EMPTY',reason:'too-little-text'};return{usable:true,code:'OK',reason:null};}
function requiresRender(page){const text=clean(page?.text||'').slice(0,1800);return /^(?:enable javascript|javascript is required|loading\.{0,3}|please wait while)(?:\s|$)/iu.test(text)||/\b(?:enable javascript|javascript is required)\s+(?:to continue|to view|to use)\b/iu.test(text);}
function needsRender(page){const text=clean(page?.text||'');return text.length<MIN_DIRECT_TEXT||requiresRender(page);}
function statusOf(error){return Number(error?.details?.status||error?.statusCode||0);}
function retryableServerError(error){const status=statusOf(error);return error?.code==='WEB_HTTP_STATUS'&&status>=500&&status<=599;}
function canRenderAfter(error){const status=statusOf(error);if(error?.code==='WEB_HTTP_STATUS'&&status>=400)return false;const info=classifyWebFailure(error);return info.category==='transient'||info.category==='content'||['WEB_CONTENT_TYPE','WEB_EXTRACT_EMPTY','WEB_ENCODING_UNSUPPORTED'].includes(error?.code);}
export function createPageReader({web,sourceOperations=createSourceOperations()}={}){
  if(!web)throw new Error('web required');
  async function read(candidate,{signal=null,question='',claims=[],onEvent=null}={}){
    const attempts=[];const started=Date.now();const originalUrl=String(candidate?.url||'');const domain=host(originalUrl);let page=null;let directError=null;let renderNeeded=false;
    const structured=candidate?.structuredEvidence;
    if(structured?.kind==='wikidata-current-office'&&clean(structured.text)&&/^Q\d+$/u.test(String(structured.officeId||''))&&/^Q\d+$/u.test(String(structured.personId||''))){
      const excerpt=clean(structured.text).slice(0,MAX_EXCERPT_CHARS);
      const result={status:'usable',url:originalUrl,domain,title:candidate.title||'',mode:'structured-api',bytes:Buffer.byteLength(excerpt),redirects:[],contentHash:hash(excerpt),textChars:excerpt.length,excerpts:[{id:'x1',text:excerpt,startOrdinal:0,score:terms([question,...claims.map(c=>c.evidenceQuery||c.text||c)]).size,exact:true,hostileInstructionDetected:false}],links:[],attempts:[{mode:'structured-api',ok:true,durationMs:Date.now()-started,url:originalUrl}],durationMs:Date.now()-started,externalTrust:'untrusted_external',sourceProfile:candidate.sourceProfile||candidate.rankFeatures?.sourceProfile||null,lineageId:candidate.lineageId||null,rankFeatures:candidate.rankFeatures||null,timestampHint:structured.retrievedAt||candidate.timestampHint||null,structuredEvidence:{kind:structured.kind,officeId:structured.officeId,personId:structured.personId,personName:clean(structured.personName),officeLabel:clean(structured.officeLabel),officeRole:clean(structured.officeRole),target:clean(structured.target),startDate:structured.startDate||null,retrievedAt:structured.retrievedAt||null}};
      await sourceOperations.record(domain,{ok:true,latencyMs:result.durationMs,renderNeeded:false}).catch(()=>{});onEvent?.('page-read',{url:result.url,title:result.title,mode:result.mode,excerptCount:1,textChars:result.textChars});return result;
    }
    onEvent?.('page-open-started',{url:originalUrl,domain,mode:'direct'});
    for(let directAttempt=1;directAttempt<=2;directAttempt+=1){
      try{const t=Date.now();page=await web.fetch(originalUrl,{signal,deadlineMs:10_000,maxBytes:3*1024*1024});attempts.push({mode:'direct',ok:true,attempt:directAttempt,durationMs:Date.now()-t,url:page.url||originalUrl});directError=null;break;}
      catch(error){directError=error;attempts.push({mode:'direct',ok:false,attempt:directAttempt,code:error?.code||'WEB_UNKNOWN',status:statusOf(error)||null});if(!(directAttempt===1&&retryableServerError(error)&&!signal?.aborted))break;onEvent?.('page-direct-retry',{url:originalUrl,reason:error?.code||'WEB_UNKNOWN',status:statusOf(error)||null,attempt:2});}
    }
    const directRequiresRender=Boolean(page&&requiresRender(page));
    renderNeeded=page?needsRender(page):canRenderAfter(directError);
    if(renderNeeded&&!signal?.aborted){onEvent?.('page-render-fallback',{url:originalUrl,reason:directError?.code||'DIRECT_INADEQUATE'});try{const t=Date.now();const rendered=await web.render(originalUrl,{signal,timeoutMs:10_000});attempts.push({mode:'render',ok:true,durationMs:Date.now()-t,url:rendered.url||originalUrl});page=rendered;directError=null;}catch(error){attempts.push({mode:'render',ok:false,code:error?.code||'WEB_UNKNOWN'});if(!page||directRequiresRender){page=null;directError=error;}}}
    if(!page){await sourceOperations.record(domain,{ok:false,latencyMs:Date.now()-started,renderNeeded,failureCode:directError?.code||'WEB_UNKNOWN'}).catch(()=>{});onEvent?.('page-unavailable',{url:originalUrl,domain,code:directError?.code||'WEB_UNKNOWN'});return{status:'unavailable',url:originalUrl,domain,attempts,failure:{code:directError?.code||'WEB_UNKNOWN',message:directError?.publicMessage||directError?.message||'Source unavailable'}};}
    onEvent?.('page-reading',{url:page.url||originalUrl,title:page.title||candidate.title||'',domain:host(page.url||originalUrl),mode:page.mode||'direct',bytes:Number(page.bytes||0)});
    const boundary=classifyPageContent(page);if(!boundary.usable){await sourceOperations.record(domain,{ok:false,latencyMs:Date.now()-started,renderNeeded:page.mode==='render',failureCode:boundary.code}).catch(()=>{});onEvent?.('page-rejected',{url:page.url||originalUrl,code:boundary.code});return{status:'rejected',url:page.url||originalUrl,domain:host(page.url||originalUrl),title:page.title||candidate.title||'',attempts,failure:{code:boundary.code,message:boundary.reason}};}
    onEvent?.('page-extracting',{url:page.url||originalUrl,title:page.title||candidate.title||'',domain:host(page.url||originalUrl),mode:page.mode||'direct'});
    const excerpts=selectRelevantExcerpts(page,{question,claims});if(!excerpts.length){await sourceOperations.record(domain,{ok:false,latencyMs:Date.now()-started,renderNeeded:page.mode==='render',failureCode:'WEB_NO_RELEVANT_EXCERPT'}).catch(()=>{});onEvent?.('page-rejected',{url:page.url||originalUrl,code:'WEB_NO_RELEVANT_EXCERPT'});return{status:'rejected',url:page.url||originalUrl,domain:host(page.url||originalUrl),title:page.title||candidate.title||'',attempts,failure:{code:'WEB_NO_RELEVANT_EXCERPT',message:'No bounded relevant passage was found.'}};}
    const result={status:'usable',url:page.url||originalUrl,domain:host(page.url||originalUrl),title:page.title||candidate.title||'',mode:page.mode||'direct',bytes:Number(page.bytes||0),redirects:page.redirects||[],contentHash:hash(clean(page.text)),textChars:clean(page.text).length,excerpts,links:Array.isArray(page.links)?page.links.slice(0,50):[],attempts,durationMs:Date.now()-started,externalTrust:'untrusted_external',sourceProfile:candidate.sourceProfile||candidate.rankFeatures?.sourceProfile||null,lineageId:candidate.lineageId||null,rankFeatures:candidate.rankFeatures||null,timestampHint:candidate.timestampHint||null};
    await sourceOperations.record(result.domain,{ok:true,latencyMs:result.durationMs,renderNeeded:result.mode==='render'}).catch(()=>{});onEvent?.('page-read',{url:result.url,title:result.title,mode:result.mode,excerptCount:excerpts.length,textChars:result.textChars});return result;
  }
  return{read};
}
