import { sha256 } from './contracts.js';
import { taskProfileFromPlan, preferredAnchorDomains } from './source-ledger.js';

export const CLAIM_STATES=Object.freeze(['unresearched','searching','weak','supported','strong','disputed','unresolved','not-applicable']);
const TERMINAL_ACCEPTABLE=new Set(['supported','strong','disputed','unresolved','not-applicable']);
const STOP_WORDS=new Set(['the','a','an','is','are','was','were','of','to','for','in','on','and','or','current','latest','official','source','report','independent','evidence','2024','2025','2026','2027']);
const LOOKUP_CLASSES=new Set(['current-office','weather-current','market-current','fx-current','date-current','service-status-current','sports-current','transit-current','event-current','retail-current','current-status','public-status']);
const EXTENDED_CLASSES=new Set(['news-current','medical-current','science-current','law-current','security-current']);
const BUDGETS=Object.freeze({
  lookup:Object.freeze({budgetClass:'lookup',targetUsefulPages:2,targetQueryPaths:3,pageSoftCap:2,querySoftCap:3,targetIndependentSources:1}),
  standard:Object.freeze({budgetClass:'standard',targetUsefulPages:3,targetQueryPaths:5,pageSoftCap:4,querySoftCap:5,targetIndependentSources:2}),
  extended:Object.freeze({budgetClass:'extended',targetUsefulPages:4,targetQueryPaths:6,pageSoftCap:5,querySoftCap:6,targetIndependentSources:2}),
});
function clean(v=''){return String(v||'').normalize('NFKC').replace(/[\u0000-\u001f\u007f]/gu,' ').replace(/\s+/gu,' ').trim();}
function taskFromQuestion(question,webPlan={}){const q=clean(question).toLowerCase();if(/\b(?:medical|medicine|disease|drug|treatment|diagnosis|symptom|health)\b/u.test(q))return'medicine';if(/\b(?:law|legal|statute|court|regulation|act|constitution)\b/u.test(q))return'law';if(/\b(?:stock|finance|revenue|earnings|valuation|company|business|market)\b/u.test(q))return'finance-business';if(/\b(?:paper|study|research|science|scientific|experiment)\b/u.test(q))return'science';return taskProfileFromPlan(webPlan);}
function freshness(question,webPlan={}){if(webPlan.freshness==='current'||/\b(?:current|currently|latest|today|now|recent|this week|2026)\b/iu.test(question))return'high';if(webPlan.freshness==='stable'||/\b(?:history|historical|founded|built|born|died|ancient|century)\b/iu.test(question))return'low';return'medium';}
function splitQuestion(question){const source=clean(question).replace(/\?+/gu,'?');const coarse=source.split(/(?:\?\s*|;\s+|\b(?:and|also)\s+(?=(?:why|who|what|when|where|how|which)\b))/iu).map(clean).filter(Boolean);if(coarse.length>1)return coarse.slice(0,8);const numbered=source.split(/\s+(?=\d+[.)]\s+)/u).map(clean).filter(Boolean);return numbered.length>1?numbered.slice(0,8):[source];}
function evidenceRequirement(task,webPlan,importance='critical'){const current=webPlan.freshness==='current';if(task==='government-public-office'||webPlan.claimClass==='current-office')return{minAccepted:1,minIndependent:1,preferredClasses:['official-primary','wire','major-independent-press'],primaryPreferred:true,current:true};if(task==='current-news'||webPlan.claimClass==='news-current')return{minAccepted:2,minIndependent:2,preferredClasses:['wire','official-primary','major-independent-press'],primaryPreferred:false,current:true};if(task==='medicine')return{minAccepted:2,minIndependent:2,preferredClasses:['regulator','academic-paper','journal','international-organization'],primaryPreferred:true,current};if(task==='law')return{minAccepted:1,minIndependent:1,preferredClasses:['official-primary','regulator','academic-paper'],primaryPreferred:true,current};if(task==='science')return{minAccepted:2,minIndependent:2,preferredClasses:['academic-paper','journal','university','standards-body'],primaryPreferred:true,current};if(task==='software')return{minAccepted:1,minIndependent:1,preferredClasses:['official-project','standards-body','specialist-publication'],primaryPreferred:true,current};if(task==='history')return{minAccepted:1,minIndependent:1,preferredClasses:['encyclopedia','academic-paper','university','official-primary'],primaryPreferred:false,current:false};return{minAccepted:importance==='critical'?1:1,minIndependent:1,preferredClasses:['official-primary','encyclopedia','major-independent-press','specialist-publication'],primaryPreferred:false,current};}
function evidenceQueryFor(text,webPlan={}){if(webPlan.claimClass==='current-office'&&webPlan.target&&webPlan.officeRole)return`current ${clean(webPlan.officeRole)} of ${clean(webPlan.target)}`;const value=clean(text);const historical=value.match(/\bwhen\s+(?:(?:was|were)\s+(.+?)|(.+?)\s+(?:was|were))\s+(?:built|constructed|completed|founded|established|opened|created)\b/iu);if(historical)return`${clean(historical[1]||historical[2])} completed year`;const correction=value.match(/^(?:no[,:]?\s+)?(.+?)\s*(?:[—–-]\s*)?(?:look\s+it\s+up|search\s+(?:for\s+)?it|check\s+it)\b/iu);if(correction&&clean(correction[1]))return clean(correction[1]);return value;}
function claimId(text,index){return `claim-${index+1}-${sha256(text).slice(0,10)}`;}
function budgetClassFor(question,webPlan,parts){let kind='standard';const c=String(webPlan.claimClass||'');const complex=parts.length>2||clean(question).length>420||/\b(?:compare|versus|why|cause|reason|controvers|debate|impact|trade-?off|evidence for|evidence against)\b/iu.test(question);if(LOOKUP_CLASSES.has(c)&&parts.length===1&&!complex)kind='lookup';if(EXTENDED_CLASSES.has(c)||complex)kind='extended';if(String(webPlan.strategy||'balanced')==='diverse')kind=kind==='lookup'?'standard':kind==='standard'?'extended':kind;return kind;}
export function researchBudgetPolicy(input={}){const source=typeof input==='string'?{budgetClass:input}:input;const key=String(source.budgetClass||'standard');const base=structuredClone(BUDGETS[key]||BUDGETS.standard);const effort=source.effort||{};const pageCap=Math.min(5,Math.max(1,Number(effort.maxPages||base.pageSoftCap)));const queryCap=Math.min(8,Math.max(1,Number(effort.maxQueries||base.querySoftCap)));return{...base,targetUsefulPages:Math.min(base.targetUsefulPages,pageCap),targetQueryPaths:Math.min(base.targetQueryPaths,queryCap),pageSoftCap:pageCap,querySoftCap:queryCap,pageHardCap:pageCap,queryHardCap:queryCap,targetIndependentSources:Math.min(base.targetIndependentSources,pageCap,2),expansionStep:0,repairReserve:0,maxRounds:Math.min(3,Math.max(1,Number(effort.maxRounds||2))),noGainTolerance:Math.min(2,Math.max(1,Number(effort.noGainTolerance||1))),maxDurationMs:Math.min(180000,Math.max(45000,Number(effort.maxDurationMs||120000)))};}
export function createResearchBrief(question,webPlan={}){const taskProfile=taskFromQuestion(question,webPlan);const parts=splitQuestion(question);const budgetClass=budgetClassFor(question,webPlan,parts);const requiredClaims=parts.map((text,index)=>({id:claimId(text,index),text,evidenceQuery:evidenceQueryFor(text,webPlan),importance:'critical',freshness:freshness(text,webPlan),status:'unresearched',supportingEvidenceIds:[],contradictingEvidenceIds:[],independenceGroups:[],resolution:null,evidenceRequirement:evidenceRequirement(taskProfile,webPlan,'critical')}));return{version:5,question:clean(question),intent:webPlan.claimClass||'web-research',freshness:freshness(question,webPlan),taskProfile,strategy:['balanced','diverse','source-first'].includes(String(webPlan.strategy))?String(webPlan.strategy):'balanced',budgetClass,effort:webPlan.effort||null,requiredClaims,preferredSourceClasses:[...new Set(requiredClaims.flatMap(c=>c.evidenceRequirement.preferredClasses))],forbiddenByUser:[],createdAt:new Date().toISOString()};}
function baseSubject(claim,brief,webPlan){if(webPlan.claimClass==='current-office'&&webPlan.target)return`${webPlan.target} ${webPlan.officeRole||'current office holder'}`;return clean(claim.evidenceQuery||claim.text||brief.question).slice(0,360);}
function fingerprint(query){return clean(query).toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').split(/\s+/u).filter(t=>t&&!STOP_WORDS.has(t)).sort().join(' ');}
export function planQueries(brief,webPlan={},{onlyClaimIds=null,includeCounter=true,resolution=false,verification=false,explorationRound=0}={}){const selected=brief.requiredClaims.filter(c=>!onlyClaimIds||onlyClaimIds.includes(c.id));const queries=[];const seenIntent=new Set();const strategy=String(webPlan.strategy||brief.strategy||'balanced');const add=(claim,intent,query,preferredClasses=[])=>{query=clean(query).slice(0,400);if(!query)return;const key=`${claim.id}:${intent}:${fingerprint(query)}`;if(seenIntent.has(key))return;seenIntent.add(key);queries.push({id:`query-${queries.length+1}-${sha256(key).slice(0,8)}`,claimIds:[claim.id],intent,query,preferredClasses,status:'planned'});};for(const claim of selected){const subject=baseSubject(claim,brief,webPlan);const anchorDomains=webPlan?.sourceConstraint?.kind==='domain'?[]:preferredAnchorDomains(brief.taskProfile,{limit:strategy==='source-first'?2:1});const anchors=()=>anchorDomains.forEach(d=>add(claim,'anchor',`site:${d} ${subject}`,claim.evidenceRequirement.preferredClasses));const direct=()=>add(claim,'direct',webPlan.query&&selected.length===1&&webPlan.claimClass!=='stable-history'?webPlan.query:subject,claim.evidenceRequirement.preferredClasses);const primary=()=>add(claim,'primary',`${subject} official`,claim.evidenceRequirement.preferredClasses.filter(x=>['official-primary','official-project','regulator','standards-body','academic-paper'].includes(x)));const independent=()=>add(claim,'independent',`${subject} independent report`,['wire','major-independent-press','journal','university']);if(strategy==='source-first'){anchors();primary();direct();independent();}else if(strategy==='diverse'){direct();independent();primary();anchors();}else{direct();primary();anchors();independent();}if(claim.freshness==='high')add(claim,'freshness',`${subject} ${new Date().getUTCFullYear()} current`,claim.evidenceRequirement.preferredClasses);if(includeCounter&&/\b(?:why|cause|reason|controvers|claim|alleg|debate|effect|impact)\b/iu.test(claim.text))add(claim,'counter',`${subject} dispute alternative explanation`,['academic-paper','major-independent-press','specialist-publication']);if(resolution)add(claim,'conflict-resolution',`${subject} conflicting reports official primary source`,claim.evidenceRequirement.preferredClasses);if(verification)add(claim,'verification',`${subject} corroboration independent confirmation`,['wire','major-independent-press','journal','university']);if(explorationRound>0){const suffixes=['reference overview','facts evidence','authoritative source','research analysis','alternative source','expert consensus','primary documentation','independent verification'];const suffix=suffixes[(explorationRound-1)%suffixes.length];add(claim,`recovery-${explorationRound}`,`${subject} ${suffix}`,claim.evidenceRequirement.preferredClasses);}}return queries;}
export function transitionClaim(claim,next,patch={}){if(!CLAIM_STATES.includes(next))throw new Error(`unknown claim state ${next}`);return{...claim,...patch,status:next};}
export function claimSufficient(claim){if(!claim||claim.importance!=='critical')return true;if(!TERMINAL_ACCEPTABLE.has(claim.status))return false;if(['supported','strong'].includes(claim.status)){const accepted=(claim.supportingEvidenceIds||[]).length;const independent=new Set(claim.independenceGroups||[]).size;return accepted>=Number(claim.evidenceRequirement?.minAccepted||1)&&independent>=Number(claim.evidenceRequirement?.minIndependent||1);}return true;}
export function researchDecision({claims=[],budget={},remainingActions=0,lastInformationGain=0}={}){const unresolved=claims.filter(c=>c.importance==='critical'&&!claimSufficient(c));const exhausted=Number(budget.queriesRemaining??1)<=0&&Number(budget.pagesRemaining??1)<=0;if(!unresolved.length)return{action:'finish',reason:'critical-claims-sufficient',claimIds:[]};if(exhausted||remainingActions<=0)return{action:'finish-partial',reason:exhausted?'budget-exhausted':'no-viable-actions',claimIds:unresolved.map(c=>c.id)};if(lastInformationGain===0&&Number(budget.noGainRounds||0)>=Number(budget.noGainTolerance||2))return{action:'finish-partial',reason:'no-information-gain',claimIds:unresolved.map(c=>c.id)};return{action:'continue',reason:'unresolved-critical-claims',claimIds:unresolved.map(c=>c.id)};}
export function plannerDiagnostics(brief,queries){return{claimCount:brief.requiredClaims.length,queryCount:queries.length,queryFamilies:[...new Set(queries.map(q=>q.intent))],freshness:brief.freshness,taskProfile:brief.taskProfile,budgetClass:brief.budgetClass,strategy:brief.strategy};}
