import { artifactEnvelope } from './contracts.js';
import { supportGuard, TRUTH_VERSION } from './support-guard.js';

function clean(v){return String(v??'').normalize('NFC').replace(/\s+/gu,' ').trim();}
function likelyFactual(text){const t=clean(text);return /\d|\b(?:is|are|was|were|has|have|became|began|ended|leads?|president|ceo|founded|released|announced|according)\b/iu.test(t)||/\b\p{Lu}[\p{L}'’-]+\s+\p{Lu}[\p{L}'’-]+/u.test(t);}
function supportText(record,excerptArtifacts){return(record.payload.excerptIds||[]).map(id=>excerptArtifacts.get(id)?.payload?.text||'').filter(Boolean);}
function sameProposition(a,b){const canon=value=>clean(value).toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();return Boolean(canon(a)&&canon(a)===canon(b));}
function verifySentence(sentence,evidenceMap,excerptMap,claimMap){const refs=sentence.evidenceIds.map(id=>evidenceMap.get(id)).filter(Boolean);if(sentence.kind==='transition'&&!likelyFactual(sentence.text)&&!refs.length)return{status:'non-factual',sentence};if(!refs.length)return{status:'unsupported',sentence,reason:'NO_EVIDENCE'};if(/\?\s*$/u.test(clean(sentence.text))||(sentence.claimIds||[]).some(id=>sameProposition(sentence.text,claimMap.get(id)?.text)))return{status:'weak',sentence,reason:'QUESTION_RESTATEMENT'};const source=refs.flatMap(r=>supportText(r,excerptMap));const support=supportGuard(sentence.text,source,'paraphrase');if(support.supported)return{status:'supported',sentence};return{status:'weak',sentence,reason:support.reason||'NOT_TRACEABLE'};}
function sourceIndex(records,dossierMap){const urls=[];const byUrl=new Map();for(const r of records){const url=r.payload.provenance?.url;if(!url)continue;if(!byUrl.has(url)){const dossier=dossierMap.get(r.payload.sourceId);const source={index:urls.length+1,url,title:dossier?.payload?.title||r.payload.provenance?.domain||url,domain:r.payload.provenance?.domain||''};byUrl.set(url,source);urls.push(source);}}return{sources:urls,byUrl};}
export function verifyAndRepair({runId,draftArtifact,claims,evidenceArtifacts,excerptArtifacts=[],dossierArtifacts=[],conflictArtifacts=[],allowedEvidenceIds=null,omittedClaimIds=[],nodeId='research-verify'}={}){
  const allowed=allowedEvidenceIds?new Set(allowedEvidenceIds):null;const evidenceMap=new Map(evidenceArtifacts.filter(a=>a.payload?.accepted&&(!allowed||allowed.has(a.artifactId))).map(a=>[a.artifactId,a]));const excerptMap=new Map(excerptArtifacts.map(a=>[a.artifactId,a]));const dossierMap=new Map(dossierArtifacts.map(a=>[a.artifactId,a]));const claimMap=new Map(claims.map(c=>[c.id,c]));const checks=draftArtifact.payload.sentences.map(s=>verifySentence(s,evidenceMap,excerptMap,claimMap));const kept=[];const repairs=[];
  for(const check of checks){if(['supported','non-factual'].includes(check.status)){kept.push(check.sentence);continue;}const refs=check.sentence.evidenceIds.map(id=>evidenceMap.get(id)).filter(Boolean);if(refs.length){const replacement=refs[0].payload.statement;const replacementSupport=supportGuard(replacement,supportText(refs[0],excerptMap),'paraphrase');if(replacement&&replacementSupport.supported){kept.push({text:replacement,evidenceIds:[refs[0].artifactId],claimIds:check.sentence.claimIds||[refs[0].payload.claimId],kind:'factual'});repairs.push({from:check.sentence.text,to:replacement,reason:check.reason});continue;}}repairs.push({from:check.sentence.text,to:null,reason:check.reason});}
  // Ensure unresolved/disputed critical claims cannot vanish just because the writer omitted them.
  const omittedSet=new Set(omittedClaimIds||[]);for(const claim of claims.filter(c=>c.importance==='critical'&&(omittedSet.has(c.id)||['disputed','unresolved','weak','unresearched'].includes(c.status)))){if(kept.some(s=>(s.claimIds||[]).includes(claim.id)&&s.kind==='qualification'))continue;const refs=[...evidenceMap.values()].filter(a=>a.payload.claimId===claim.id);const text=omittedSet.has(claim.id)?`I could not include enough verified evidence for ${claim.text.replace(/[?.!]+$/u,'')} within the selected model context.`:claim.status==='disputed'?`The available sources disagree on ${claim.text.replace(/[?.!]+$/u,'')}.`:`I could not verify ${claim.text.replace(/[?.!]+$/u,'')} reliably from the available evidence.`;kept.push({text,evidenceIds:omittedSet.has(claim.id)?[]:refs.map(a=>a.artifactId).slice(0,4),claimIds:[claim.id],kind:'qualification'});}
  const usedRecords=[...new Map(kept.flatMap(s=>s.evidenceIds).map(id=>[id,evidenceMap.get(id)]).filter(([,v])=>v)).values()];const idx=sourceIndex(usedRecords,dossierMap);const lines=kept.map(s=>{const nums=[...new Set(s.evidenceIds.map(id=>evidenceMap.get(id)?.payload?.provenance?.url).filter(Boolean).map(url=>idx.byUrl.get(url)?.index).filter(Boolean))];return `${clean(s.text)}${nums.length?` ${nums.map(n=>`[${n}]`).join('')}`:''}`;});const answer=lines.join('\n\n').trim();const unsupported=checks.filter(x=>!['supported','non-factual'].includes(x.status));const unresolvedClaims=[...new Set([...claims.filter(c=>c.importance==='critical'&&!['supported','strong'].includes(c.status)).map(c=>c.id),...omittedSet])];const verification=artifactEnvelope({type:'VerificationResult',runId,nodeId,payload:{truthVersion:TRUTH_VERSION,checks:checks.map(c=>({status:c.status,text:c.sentence.text,evidenceIds:c.sentence.evidenceIds,reason:c.reason||null})),repairs,unsupportedCount:unsupported.length,unresolvedClaimIds:unresolvedClaims,conflictIds:conflictArtifacts.map(a=>a.artifactId),passed:unsupported.length===0||repairs.length>=unsupported.length},inputRefs:[draftArtifact.artifactId,...usedRecords.map(a=>a.artifactId),...conflictArtifacts.map(a=>a.artifactId)],retentionClass:'interrupted-run'});const final=artifactEnvelope({type:'VerifiedAnswer',runId,nodeId:'research-final',payload:{truthVersion:TRUTH_VERSION,answer,sources:idx.sources,verificationId:verification.artifactId,usedEvidenceIds:usedRecords.map(a=>a.artifactId),partial:unresolvedClaims.length>0},inputRefs:[verification.artifactId,draftArtifact.artifactId,...usedRecords.map(a=>a.artifactId)],retentionClass:'chat-compact'});return{verification,final,needsFollowupClaimIds:unresolvedClaims.filter(id=>claims.find(c=>c.id===id)?.status==='weak')};
}
