import { canonicalizeUrl } from './discovery.js';
import { sourceProfileFor } from '../research/source-ledger.js';
const SEARCH_HOSTS=new Set(['duckduckgo.com','html.duckduckgo.com','google.com','bing.com','search.brave.com','mojeek.com']);
const STOP=new Set(['the','a','an','is','are','was','were','who','what','when','where','why','how','of','for','in','on','to','and','or','current','latest','today','now','official','site']);
function domainOf(url){try{return new URL(url).hostname.toLowerCase().replace(/^www\./u,'');}catch{return'';}}
function toks(value=''){return String(value).normalize('NFKC').toLocaleLowerCase('en').replace(/[^\p{L}\p{N}]+/gu,' ').split(/\s+/u).filter(t=>t&&!STOP.has(t));}
function overlap(query,candidate){const q=new Set(toks(query));if(!q.size)return 0;const c=new Set(toks(candidate));let hit=0;for(const t of q)if(c.has(t))hit+=1;return hit/q.size;}
function freshnessTier(plan,value){if(plan?.freshness!=='current')return 1;const n=Date.parse(String(value||''));if(!Number.isFinite(n))return 2;const days=Math.max(0,(Date.now()-n)/86400000);if(days<=2)return 0;if(days<=30)return 1;if(days<=365)return 2;return 4;}
function relevanceTier(value){if(value>=.75)return 0;if(value>=.45)return 1;if(value>=.2)return 2;if(value>0)return 3;return 5;}
function roleTier(profile){if(profile.evidenceRole==='primary'||String(profile.evidenceRole||'').startsWith('primary'))return 0;if(profile.discoveryRole==='orientation')return 2;return 1;}
function strategyTier(profile,plan,relevance=0){const strategy=String(plan?.strategy||'balanced');if(strategy!=='source-first')return profile.anchor?0:1;const primary=String(profile.evidenceRole||'').startsWith('primary')||profile.classIds?.some(cls=>['official-primary','regulator','standards-body','academic-paper','official-project'].includes(cls));if((primary||profile.anchor)&&relevance>=.2)return 0;return primary||profile.anchor?2:1;}
function constraintTier(domain,plan){if(plan?.sourceConstraint?.kind!=='domain')return 0;const wanted=String(plan.sourceConstraint.domain||'').toLowerCase();const match=domain===wanted||domain.endsWith(`.${wanted}`);return match?0:(plan.sourceConstraint.strictFirst?2:1);}
function availabilityTier(profile){const rate=profile.operationalStats?.successRate;if(rate==null)return 1;if(rate>=.75)return 0;if(rate>=.35)return 1;return 2;}
export function candidateFeatures(candidate,plan,{operationalStats=null}={}){const domain=domainOf(candidate.url);const text=`${candidate.title||''} ${candidate.snippet||''} ${domain} ${candidate.url||''}`;const relevance=overlap(plan?.query||plan?.target||'',text);const profile=sourceProfileFor({domain},plan,{},operationalStats);const structuredTier=candidate?.structuredEvidence?.kind==='wikidata-current-office'?0:1;return{domain,relevance,profile,structuredTier,searchHost:SEARCH_HOSTS.has(domain),excluded:(plan?.excludeDomains||[]).some(d=>domain===d||domain.endsWith(`.${d}`)),freshnessTier:freshnessTier(plan,candidate.timestampHint),relevanceTier:relevanceTier(relevance),constraintTier:constraintTier(domain,plan),roleTier:roleTier(profile),strategyTier:strategyTier(profile,plan,relevance),availabilityTier:availabilityTier(profile),engineRank:Math.max(1,Number(candidate.engineRank||999))};}
export function priorityTuple(candidate,plan,options={}){const f=candidateFeatures(candidate,plan,options);return{features:f,tuple:[f.constraintTier,f.structuredTier,f.relevanceTier,f.freshnessTier,f.profile.taskTier,f.strategyTier,f.roleTier,f.availabilityTier,f.engineRank]};}
function compareTuple(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=Number(a[i]??0)-Number(b[i]??0);if(d)return d;}return 0;}
export function scoreCandidate(candidate,plan,options={}){const {features,tuple}=priorityTuple(candidate,plan,options);const blocked=features.searchHost||features.excluded;let ordinal=0;for(let i=0;i<tuple.length;i++)ordinal=ordinal*1000+Math.min(999,Math.max(0,Number(tuple[i]||0)));return{score:blocked?Number.NEGATIVE_INFINITY:-ordinal,blocked,features,priorityTuple:tuple};}
export function rankCandidates(candidates,plan,{limit=12,operationalByDomain={}}={}){const dedup=new Map();for(const item of candidates||[]){let url;try{url=canonicalizeUrl(item.url);}catch{continue;}const existing=dedup.get(url);const next={...item,url};if(!existing||Number(next.engineRank||999)<Number(existing.engineRank||999))dedup.set(url,next);}const rows=[];for(const c of dedup.values()){const domain=domainOf(c.url);const {blocked,features,priorityTuple:tuple}=scoreCandidate(c,plan,{operationalStats:operationalByDomain[domain]||null});if(blocked)continue;rows.push({...c,domain,rankFeatures:{relevance:features.relevance,sourceProfile:features.profile,priorityTuple:tuple},sourceProfile:features.profile,priorityTuple:tuple,priorityWhy:features.profile.why});}rows.sort((a,b)=>compareTuple(a.priorityTuple,b.priorityTuple)||a.url.localeCompare(b.url));const out=[];const publisherCounts=new Map();const domainCounts=new Map();const diverse=String(plan?.strategy||'balanced')==='diverse';for(const row of rows){if(out.length>=limit)break;const publisher=row.publisherGroup||row.domain;const pubRepeats=publisherCounts.get(publisher)||0;const domainRepeats=domainCounts.get(row.domain)||0;if(diverse&&pubRepeats>=1)continue;if(!diverse&&domainRepeats>=2)continue;out.push(row);publisherCounts.set(publisher,pubRepeats+1);domainCounts.set(row.domain,domainRepeats+1);}return out;}
