import net from 'node:net';
import tls from 'node:tls';
import { fail } from '../lib/errors.js';

const MAX_PROXY_HEADER=16*1024;
function abortError(){return fail('WEB_CANCELLED','Web work was stopped.',499);}
export function parseUpstreamProxy(input){
  if(!input)return null;let url;try{url=new URL(String(input));}catch{throw fail('WEB_PROXY_URL','Enter a valid HTTP, HTTPS or SOCKS5 proxy URL.',400);}
  if(!['http:','https:','socks5:'].includes(url.protocol))throw fail('WEB_PROXY_URL','Only HTTP, HTTPS and SOCKS5 static proxies are supported.',400);
  if(url.username||url.password)throw fail('WEB_PROXY_AUTH_UNSUPPORTED','Authenticated proxies are not supported in this build. KL01 will not bypass them with a direct connection.',409);
  if((url.pathname&&url.pathname!=='/')||url.search||url.hash)throw fail('WEB_PROXY_URL','Proxy URL must contain only scheme, host and port.',400);
  const port=Number(url.port||({ 'http:':80,'https:':443,'socks5:':1080 }[url.protocol]));if(!Number.isInteger(port)||port<1||port>65535)throw fail('WEB_PROXY_URL','Proxy port is invalid.',400);
  const host=url.hostname.startsWith('[')&&url.hostname.endsWith(']')?url.hostname.slice(1,-1):url.hostname;
  return {type:url.protocol.slice(0,-1),host,port};
}

export function formatUpstreamProxy(value){
  const proxy=value&&typeof value==='object'&&value.type?value:parseUpstreamProxy(value);
  if(!proxy)return null;
  const host=net.isIP(proxy.host)===6?`[${proxy.host}]`:proxy.host;
  return `${proxy.type}://${host}:${proxy.port}`;
}
function connectProxy(proxy,{signal,timeoutMs=5000}={}){return new Promise((resolve,reject)=>{
  if(signal?.aborted)return reject(abortError());let settled=false;const options={host:proxy.host,port:proxy.port};if(proxy.type==='https')options.servername=proxy.host;
  const socket=proxy.type==='https'?tls.connect(options):net.connect(options);const timer=setTimeout(()=>{socket.destroy();done(reject,fail('WEB_PROXY_CONNECT','KL01 could not connect to the configured proxy.',502));},timeoutMs);
  const done=(fn,v)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);socket.off('error',error);socket.off(proxy.type==='https'?'secureConnect':'connect',connected);fn(v);};
  const abort=()=>{socket.destroy();done(reject,abortError());};const error=e=>done(reject,fail('WEB_PROXY_CONNECT','KL01 could not connect to the configured proxy.',502,undefined,e));const connected=()=>{socket.on('error',()=>{});done(resolve,socket);};
  socket.once('error',error);socket.once(proxy.type==='https'?'secureConnect':'connect',connected);signal?.addEventListener('abort',abort,{once:true});
});}
function readUntil(socket,marker,{signal,limit=MAX_PROXY_HEADER,timeoutMs=5000}={}){return new Promise((resolve,reject)=>{let chunks=[],size=0,settled=false;const timer=setTimeout(()=>done(reject,fail('WEB_PROXY_TIMEOUT','The configured proxy did not respond in time.',504)),timeoutMs);const done=(fn,v)=>{if(settled)return;settled=true;clearTimeout(timer);socket.off('data',data);socket.off('error',error);signal?.removeEventListener('abort',abort);fn(v)};const data=c=>{chunks.push(c);size+=c.length;if(size>limit)return done(reject,fail('WEB_PROXY_PROTOCOL','The proxy response was too large.',502));const b=Buffer.concat(chunks);const i=b.indexOf(marker);if(i>=0){const rest=b.subarray(i+marker.length);const value=b.subarray(0,i+marker.length);done(resolve,value);if(rest.length)socket.unshift(rest);}};const error=e=>done(reject,fail('WEB_PROXY_CONNECT','The proxy connection failed.',502,undefined,e));const abort=()=>{socket.destroy();done(reject,abortError())};socket.on('data',data);socket.once('error',error);signal?.addEventListener('abort',abort,{once:true});});}
function readExact(socket,count,{signal,timeoutMs=5000}={}){return new Promise((resolve,reject)=>{let settled=false;const timer=setTimeout(()=>done(reject,fail('WEB_PROXY_TIMEOUT','The configured proxy did not respond in time.',504)),timeoutMs);const done=(fn,v)=>{if(settled)return;settled=true;clearTimeout(timer);socket.off('readable',readable);socket.off('error',error);socket.off('close',closed);socket.off('end',closed);signal?.removeEventListener('abort',abort);fn(v)};const tryRead=()=>{const value=socket.read(count);if(value?.length===count){done(resolve,value);return true;}return false;};const readable=()=>{tryRead();};const error=e=>done(reject,fail('WEB_PROXY_CONNECT','The proxy connection failed.',502,undefined,e));const closed=()=>done(reject,fail('WEB_PROXY_CONNECT','The proxy connection closed before setup completed.',502));const abort=()=>{socket.destroy();done(reject,abortError())};socket.on('readable',readable);socket.once('error',error);socket.once('close',closed);socket.once('end',closed);signal?.addEventListener('abort',abort,{once:true});tryRead();});}
function ipv6Bytes(value){const [left,right='']=String(value).split('::');const l=left?left.split(':').filter(Boolean):[],r=right?right.split(':').filter(Boolean):[];const missing=8-l.length-r.length;if(missing<0)throw new Error('ipv6');const groups=[...l,...Array(missing).fill('0'),...r];if(groups.length!==8)throw new Error('ipv6');const out=Buffer.alloc(16);groups.forEach((g,i)=>out.writeUInt16BE(parseInt(g||'0',16),i*2));return out;}
async function httpTunnel(proxy,target,port,options){const socket=await connectProxy(proxy,options);try{const authority=target.includes(':')?`[${target}]:${port}`:`${target}:${port}`;socket.write(`CONNECT ${authority} HTTP/1.1\r\nHost: ${authority}\r\nProxy-Connection: keep-alive\r\n\r\n`);const head=(await readUntil(socket,Buffer.from('\r\n\r\n'),options)).toString('latin1');const m=head.match(/^HTTP\/\d(?:\.\d)?\s+(\d{3})/u);const status=Number(m?.[1]||0);if(status===407)throw fail('WEB_PROXY_AUTH_REQUIRED','The configured proxy requires authentication, which this build does not support. KL01 did not fall back to direct internet.',409);if(status!==200)throw fail('WEB_PROXY_CONNECT',`The configured proxy refused the tunnel (HTTP ${status||'invalid'}).`,502,{status});return socket;}catch(e){socket.destroy();throw e;}}
async function socksTunnel(proxy,target,port,options){const socket=await connectProxy(proxy,options);try{socket.write(Buffer.from([5,1,0]));const hello=await readExact(socket,2,options);if(hello[0]!==5||hello[1]!==0)throw fail('WEB_PROXY_AUTH_REQUIRED','The configured SOCKS5 proxy requires unsupported authentication. KL01 did not fall back to direct internet.',409);const family=net.isIP(target);let addr;if(family===4)addr=Buffer.from([1,...target.split('.').map(Number)]);else if(family===6)addr=Buffer.concat([Buffer.from([4]),ipv6Bytes(target)]);else throw fail('WEB_PROXY_PROTOCOL','KL01 only sends pre-vetted numeric destinations to an upstream proxy.',502);const tail=Buffer.alloc(2);tail.writeUInt16BE(port);socket.write(Buffer.concat([Buffer.from([5,1,0]),addr,tail]));const first=await readExact(socket,4,options);if(first[0]!==5||first[1]!==0)throw fail('WEB_PROXY_CONNECT','The configured SOCKS5 proxy refused the tunnel.',502,{reply:first[1]});let boundBytes;if(first[3]===1)boundBytes=4;else if(first[3]===4)boundBytes=16;else if(first[3]===3)boundBytes=(await readExact(socket,1,options))[0];else throw fail('WEB_PROXY_PROTOCOL','The configured SOCKS5 proxy returned an invalid address type.',502,{addressType:first[3]});if(boundBytes)await readExact(socket,boundBytes,options);await readExact(socket,2,options);return socket;}catch(e){socket.destroy();throw e;}}
export async function connectThroughProxy(proxyInput,addresses,port,options={}){const proxy=proxyInput&&typeof proxyInput==='object'&&proxyInput.type?proxyInput:parseUpstreamProxy(proxyInput);if(!proxy)throw fail('WEB_PROXY_URL','No upstream proxy is configured.',400);let last;for(const address of addresses){try{return await (proxy.type==='socks5'?socksTunnel(proxy,address.address,port,options):httpTunnel(proxy,address.address,port,options));}catch(e){last=e;if(options.signal?.aborted||e?.code==='WEB_PROXY_AUTH_REQUIRED')throw e;}}throw last||fail('WEB_PROXY_CONNECT','The configured proxy could not reach the public destination.',502);}
