import fs from 'node:fs/promises';
export const HOST = '127.0.0.1';
export const DEFAULT_PORT = 3210;
export const DATA_SCHEMA_VERSION = 1;
export const MAX_REQUEST_BYTES = 15 * 1024 * 1024;
export const DOWNLOAD_HEADROOM_BYTES = 512 * 1024 * 1024;
export const DOWNLOAD_BACKOFF_MS = [2_000, 5_000, 15_000, 30_000, 60_000];
export const CONTEXT_THRESHOLDS = Object.freeze({ quiet: 0.70, long: 0.85, full: 1 });
export const PARTIAL_PERSIST_MS = 750;
export const SSE_HEARTBEAT_MS = 15_000;
export const WORK_EVENT_REPLAY_LIMIT = 1200;
export const WORK_RUN_RECOVERY_MS = 30 * 60 * 1000;
export const WORK_HEARTBEAT_MS = 3_000;
export const WEB_OPERATION_STALL_MS = 10_000;
export const RUNTIME_READY_TIMEOUT_MS = 120_000;
export const RUNTIME_STOP_TIMEOUT_MS = 15_000;
export const LLAMA_RELEASE_TAG = 'b10107';
export const LLAMA_WINDOWS_ASSET = 'llama-b10107-bin-win-cpu-x64.zip';
export const LLAMA_WINDOWS_URL = `https://github.com/ggml-org/llama.cpp/releases/download/${LLAMA_RELEASE_TAG}/${LLAMA_WINDOWS_ASSET}`;
export const LLAMA_WINDOWS_SIZE = 18_213_827;
export const LLAMA_WINDOWS_SHA256 = '52133a0a5a8f6035b1bdd2f89c3425ea8b742413d9bdb9a2dee30e3a1681b18c';
export const LLAMA_BINARY_NAME = process.platform === 'win32' ? 'llama-server.exe' : 'llama-server';
export const DEFAULT_CONTEXT_SIZE = 8_192;
export const MAX_GENERATION_TOKENS = 2_048;
const PACKAGE = JSON.parse(await fs.readFile(new URL('../package.json', import.meta.url), 'utf8'));
const PRODUCT = JSON.parse(await fs.readFile(new URL('../product.json', import.meta.url), 'utf8'));
export const BUILD_VERSION = PACKAGE.version;
export const PRODUCT_NAME = PRODUCT.name;
export const PRODUCT_STAGE = PRODUCT.stage;
export const PRODUCT_APP_ID = PRODUCT.appId;
export const BUG_REPORT_EMAIL = PRODUCT.bugReportEmail;
export const USER_AGENT = `${PRODUCT_NAME} Pre Beta (local desktop Web; https://kondalabs.com)`;

export const MODEL_APP_MEMORY_RESERVE_BYTES = 512 * 1024 * 1024;
export const MODEL_MEMORY_HEADROOM_RATIO = 0.5;
