import { compatibility } from '../execution/target-descriptor.js';
import { buildBuiltinWorkflow, isWorkflowMode } from './builtins.js';
import { normalizeOrMigrateWorkflow } from './migrate-v1.js';
import { compileWorkflowDefinition } from './compiler.js';

const clone=v=>structuredClone(v);
function resolve(modeId,workflow,slotTargets){return workflow?normalizeOrMigrateWorkflow(workflow).workflow:buildBuiltinWorkflow(modeId,{slotTargets});}
function mergeReq(a={},b={}){return{inputModalities:[...new Set([...(a.inputModalities||['text']),...(b.inputModalities||[])])],fileTypes:[...new Set([...(a.fileTypes||[]),...(b.fileTypes||[])])],structuredOutput:Boolean(a.structuredOutput||b.structuredOutput),reasoning:Boolean(a.reasoning||b.reasoning),contextTokens:Math.max(Number(a.contextTokens||0),Number(b.contextTokens||0))};}
export async function preflightWorkflow({modeId='standard',workflow=null,slotTargets={},webPlan=null,targetManager,governor,allowCompatibleFallback=true}={}){
  if(!workflow&&!isWorkflowMode(modeId))return{runnable:true,isWorkflow:false,modeId,effectiveExecution:'sequential',slots:[],warnings:[]};
  const definition=resolve(modeId,workflow,slotTargets);const compiled=compileWorkflowDefinition(definition,{webPlan,slotTargets,allowCompatibleFallback});const descriptors=targetManager?await targetManager.descriptors():[];const preference=targetManager?await targetManager.preference():null;const resource=governor?await governor.detailedSnapshot():null;const slotRows=[];let runnable=true;
  for(const slot of definition.slots){const requirements=compiled.graph.nodes.filter(n=>n.targetPolicy?.slotId===slot.id).reduce((acc,n)=>mergeReq(acc,n.capabilityRequirements),slot.capabilityRequirements||{});const explicit=String(slotTargets?.[slot.id]||slot.targetPolicy?.targetId||'').trim();const desired=explicit?descriptors.find(d=>d.targetId===explicit):preference;const compatible=descriptors.filter(d=>compatibility(d,requirements).ok&&!d.state?.pendingRemoval);const fallbackAllowed=Boolean(allowCompatibleFallback)&&slot.fallbackPolicy?.allowFallback!==false;let planned=desired&&compatibility(desired,requirements).ok&&!desired.state?.pendingRemoval?desired:null;let reusedOnly=false;let fallbackPlanned=false;
    if(!planned&&fallbackAllowed&&compatible.length){planned=compatible[0];reusedOnly=!explicit&&compatible.length===1;fallbackPlanned=Boolean(desired&&planned.targetId!==desired.targetId)||Boolean(explicit&&!desired);}
    const issues=[];if(explicit&&!desired)issues.push({code:'WORKFLOW_TARGET_MISSING',message:'Assigned target is no longer available.'});else if(desired&&!compatibility(desired,requirements).ok)issues.push(...compatibility(desired,requirements).reasons);if(!planned){runnable=false;issues.push({code:fallbackAllowed?'MODEL_FALLBACK_NONE':'MODEL_FALLBACK_DISABLED',message:fallbackAllowed?'No compatible installed target can run this slot.':'The requested target cannot run this slot and compatible fallback is disabled in Settings.'});}
    slotRows.push({id:slot.id,label:slot.label,role:slot.role,requirements,requestedTargetId:explicit||preference?.targetId||null,plannedTarget:planned?{targetId:planned.targetId,name:planned.name,kind:planned.kind,state:clone(planned.state)}:null,compatibleTargetIds:compatible.map(d=>d.targetId),fallbackAllowed,reuseSoleCompatible:reusedOnly,fallbackPlanned,issues});
  }
  const modelNodes=compiled.graph.nodes.filter(n=>n.type==='model');const roots=modelNodes.filter(n=>!n.dependencies.some(id=>modelNodes.some(m=>m.id===id)));const uniqueTargets=new Set(slotRows.map(r=>r.plannedTarget?.targetId).filter(Boolean));let effectiveExecution='sequential';if(roots.length>1&&runnable){if(uniqueTargets.size>1)effectiveExecution='parallel-possible';else if(uniqueTargets.size===1){const d=descriptors.find(x=>x.targetId===[...uniqueTargets][0]);effectiveExecution=Number(d?.runtime?.parallelVerified?d.runtime.parallelCapacity:1)>1?'parallel-possible':'sequential';}else effectiveExecution='mixed';}
  const hasRequiredResearch=definition.nodes.some(n=>n.type==='research'&&n.webPolicy?.mode==='required');const webPlanKnown=webPlan!==null&&webPlan!==undefined;const researchDisabled=hasRequiredResearch&&webPlanKnown&&!webPlan?.useWeb&&webPlan?.activation==='disabled';if(researchDisabled)runnable=false;
  return{version:2,isWorkflow:true,modeId:definition.modeId||modeId,definitionId:definition.id||null,family:definition.family,label:definition.name,runnable,effectiveExecution,web:{required:hasRequiredResearch,planned:Boolean(webPlan?.useWeb),planKnown:webPlanKnown,activation:webPlan?.activation||null},slots:slotRows,nodes:compiled.graph.nodes.map(n=>({id:n.id,type:n.type,label:n.metadata.workflowNode?.label||n.id,dependencies:n.dependencies,joinPolicy:n.joinPolicy,slotId:n.targetPolicy?.slotId||null,targetId:n.targetPolicy?.targetId||null})),resources:resource?{estimated:Boolean(resource.machine?.estimated),memoryAvailable:resource.machine?.memoryAvailable||null,activeReservations:resource.reservations?.length||0}:null,warnings:[...(!runnable?[{code:'WORKFLOW_NOT_RUNNABLE',message:researchDisabled?'This workflow requires Research, but this run is explicitly set to stay local.':'Resolve the incompatible model or resource requirements before running.'}]:[]),...(researchDisabled?[{code:'WORKFLOW_RESEARCH_POLICY',message:'Research is required by this workflow but disabled for this run.'}]:[]) ]};
}
