import crypto from 'node:crypto';
import { RECIPES_FILE } from '../lib/paths.js';
import { readJson, writeJson } from './store.js';
import { fail, publicError } from '../lib/errors.js';
import { normalizeOrMigrateWorkflow } from '../workflows/migrate-v1.js';

const EMPTY={version:2,recipes:[]};const now=()=>new Date().toISOString();const recipeId=()=>`recipe-${crypto.randomBytes(8).toString('hex')}`;let queue=Promise.resolve();
function mutate(work){const next=queue.then(work,work);queue=next.catch(()=>{});return next;}
function cleanTags(input){return Array.isArray(input)?[...new Set(input.map(v=>String(v||'').trim().slice(0,40)).filter(Boolean))].slice(0,12):[];}
function normalizeRecipe(input,existing=null){const {workflow,migration}=normalizeOrMigrateWorkflow(input?.workflow||input||{});const timestamp=now();return{version:2,id:existing?.id||(/^recipe-[a-zA-Z0-9_-]+$/u.test(String(input?.id||''))?String(input.id):recipeId()),name:String(input?.name||workflow.name||'Workflow recipe').trim().slice(0,100)||'Workflow recipe',description:String(input?.description||workflow.description||'').trim().slice(0,500),tags:cleanTags(input?.tags),createdAt:existing?.createdAt||timestamp,updatedAt:timestamp,migrationStatus:'ready',migration:migration?structuredClone(migration):null,workflow:{...workflow,id:null,createdAt:null,updatedAt:null}};}
function incompatibleRecipe(raw,error){return{version:2,id:String(raw?.id||recipeId()),name:String(raw?.name||'Incompatible workflow recipe').slice(0,100),description:String(raw?.description||'').slice(0,500),tags:cleanTags(raw?.tags),createdAt:raw?.createdAt||null,updatedAt:raw?.updatedAt||null,migrationStatus:'incompatible',migrationError:publicError(error),legacyWorkflow:structuredClone(raw?.workflow||raw||null),workflow:null};}
async function readAndMigrate(){const raw=await readJson(RECIPES_FILE,{version:1,recipes:[]});const items=Array.isArray(raw?.recipes)?raw.recipes:[];let changed=Number(raw?.version||1)!==2;const migrated=[];for(const item of items){if(Number(item?.version)===2&&item?.migrationStatus==='incompatible'){migrated.push(item);continue;}try{const normalized=normalizeRecipe(item,item);if(Number(item?.workflow?.version)!==2||Number(item?.version)!==2||item?.migrationStatus!=='ready')changed=true;migrated.push(normalized);}catch(error){changed=true;migrated.push(incompatibleRecipe(item,error));}}
  const store={version:2,recipes:migrated};if(changed)await writeJson(RECIPES_FILE,store);return store;}
export async function migrateRecipes(){return mutate(async()=>{const store=await readAndMigrate();return{version:2,total:store.recipes.length,ready:store.recipes.filter(r=>r.migrationStatus!=='incompatible').length,incompatible:store.recipes.filter(r=>r.migrationStatus==='incompatible').length};});}
export async function listRecipes(){return structuredClone((await readAndMigrate()).recipes.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))));}
export async function getRecipe(id){const item=(await readAndMigrate()).recipes.find(r=>r.id===String(id));if(!item)throw fail('RECIPE_NOT_FOUND','This workflow recipe no longer exists.',404);if(item.migrationStatus==='incompatible')throw fail('RECIPE_MIGRATION_REQUIRED',item.migrationError?.message||'This saved workflow cannot be migrated safely.',409,{recipeId:item.id,migrationError:item.migrationError});return structuredClone(item);}
export async function createRecipe(input){return mutate(async()=>{const store=await readAndMigrate();const recipe=normalizeRecipe(input);store.recipes.unshift(recipe);await writeJson(RECIPES_FILE,store);return structuredClone(recipe);});}
export async function updateRecipe(id,input){return mutate(async()=>{const store=await readAndMigrate();const index=store.recipes.findIndex(r=>r.id===String(id));if(index<0)throw fail('RECIPE_NOT_FOUND','This workflow recipe no longer exists.',404);const recipe=normalizeRecipe(input,store.recipes[index]);store.recipes[index]=recipe;await writeJson(RECIPES_FILE,store);return structuredClone(recipe);});}
export async function deleteRecipe(id){return mutate(async()=>{const store=await readAndMigrate();const before=store.recipes.length;store.recipes=store.recipes.filter(r=>r.id!==String(id));if(store.recipes.length===before)throw fail('RECIPE_NOT_FOUND','This workflow recipe no longer exists.',404);await writeJson(RECIPES_FILE,store);return{deleted:String(id)};});}
const FORBIDDEN_IMPORT_KEYS=/^(?:api[-_]?key|access[-_]?token|refresh[-_]?token|auth[-_]?token|authorization|password|passwd|secret|secrets|client[-_]?secret|credential|credentials|cookie|cookies|private[-_]?key)$/iu;const UNSAFE_OBJECT_KEYS=new Set(['__proto__','prototype','constructor']);
function assertSafeImportedValue(value,path='recipe',seen=new WeakSet()){if(value===null||typeof value!=='object')return;if(seen.has(value))throw fail('RECIPE_IMPORT_CYCLE','Imported recipe JSON cannot contain cycles.',400);seen.add(value);for(const [key,child] of Object.entries(value)){if(UNSAFE_OBJECT_KEYS.has(key)||FORBIDDEN_IMPORT_KEYS.test(key))throw fail('RECIPE_IMPORT_SECRET',`Recipes cannot contain credentials, secrets, or unsafe object keys (${path}.${key}).`,400);assertSafeImportedValue(child,`${path}.${key}`,seen);}seen.delete(value);}
export async function importRecipe(input){if(!input||typeof input!=='object'||Array.isArray(input))throw fail('RECIPE_IMPORT_SHAPE','Imported recipe JSON must be an object.',400);assertSafeImportedValue(input);return createRecipe(input);}
